# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [3]:
%pip install statsmodels

Note: you may need to restart the kernel to use updated packages.


In [78]:
import numpy as np
import pandas as pd
from scipy.stats import f_oneway, norm, f, chi2, chi2_contingency
import warnings
warnings.simplefilter('ignore')
import statsmodels.api as sm
from statsmodels.formula.api import ols
from scipy.stats import ttest_ind
from scipy.stats import ttest_rel
from scipy.stats import ttest_1samp
from scipy.stats import chi2_contingency
from statsmodels.stats import weightstats as w



# Challenge 1 - Independent Sample T-tests

In this challenge, we will be using the Pokemon dataset. Before applying statistical methods to this data, let's first examine the data.

To load the data, run the code below.

In [106]:
pwd

'C:\\Users\\javip\\Lab1\\Laboratorios\\6.3-lab_two_sample_hypothesis_test\\your-code'

In [110]:
# Run this code:

pokemon = pd.read_csv(r'C:\Users\javip\Lab1\Laboratorios\6.3-lab_two_sample_hypothesis_test\pokemon.csv')

Let's start off by looking at the `head` function in the cell below.

In [5]:
pokemon.head()


#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

In [14]:
pokemon.shape

(800, 13)

The first thing we would like to do is compare the legendary Pokemon to the regular Pokemon. To do this, we should examine the data further. What is the count of legendary vs. non legendary Pokemons?

In [11]:
normales = pokemon[(pokemon.Legendary == False)]
legendarios = pokemon[(pokemon.Legendary == True)]


In [13]:
len(legendarios)

65

In [15]:
len(normales)

735

Compute the mean and standard deviation of the total points for both legendary and non-legendary Pokemon.

In [16]:
legendarios.describe()



#       Total          HP      Attack     Defense     Sp. Atk  \
count   65.000000   65.000000   65.000000   65.000000   65.000000   65.000000   
mean   470.215385  637.384615   92.738462  116.676923   99.661538  122.184615   
std    173.651095   60.937389   21.722164   30.348037   28.255131   31.104608   
min    144.000000  580.000000   50.000000   50.000000   20.000000   50.000000   
25%    381.000000  580.000000   80.000000  100.000000   90.000000  100.000000   
50%    483.000000  600.000000   91.000000  110.000000  100.000000  120.000000   
75%    642.000000  680.000000  105.000000  131.000000  115.000000  150.000000   
max    721.000000  780.000000  150.000000  190.000000  200.000000  194.000000   

          Sp. Def       Speed  Generation  
count   65.000000   65.000000   65.000000  
mean   105.938462  100.184615    3.769231  
std     28.827004   22.952323    1.455262  
min     20.000000   50.000000    1.000000  
25%     90.000000   90.000000    3.000000  
50%    100.000000  100.000000    4.000000  
75%    120.000000  110.000000    5.000000  
max    200.000000  180.000000    6.000000

In [19]:
normales.describe()

#       Total          HP      Attack     Defense     Sp. Atk  \
count  735.000000  735.000000  735.000000  735.000000  735.000000  735.000000   
mean   353.315646  417.213605   67.182313   75.669388   71.559184   68.454422   
std    208.590419  106.760417   24.808849   30.490153   30.408194   29.091705   
min      1.000000  180.000000    1.000000    5.000000    5.000000   10.000000   
25%    175.500000  324.000000   50.000000   54.500000   50.000000   45.000000   
50%    346.000000  425.000000   65.000000   72.000000   66.000000   65.000000   
75%    533.500000  498.000000   79.500000   95.000000   85.000000   85.000000   
max    715.000000  700.000000  255.000000  185.000000  230.000000  175.000000   

          Sp. Def       Speed  Generation  
count  735.000000  735.000000  735.000000  
mean    68.892517   65.455782    3.284354  
std     25.669310   27.843038    1.673471  
min     20.000000    5.000000    1.000000  
25%     50.000000   45.000000    2.000000  
50%     65.000000   64.000000    3.000000  
75%     85.000000   85.000000    5.000000  
max    230.000000  160.000000    6.000000

The computation of the mean might give us a clue regarding how the statistical test may turn out; However, it certainly does not prove whether there is a significant difference between the two groups.

In the cell below, use the `ttest_ind` function in `scipy.stats` to compare the the total points for legendary and non-legendary Pokemon. Since we do not have any information about the population, assume the variances are not equal.

In [20]:
normales.Total.mean()

417.21360544217686

In [21]:
legendarios.Total.mean()

637.3846153846154

In [24]:
test = ttest_ind(legendarios['Total'],normales['Total'])

In [34]:
test.pvalue

3.0952457469652825e-52

In [33]:
test.pvalue
test.pvalue < 0.05

True

In [27]:
test.statistic

16.386116965872425

What do you conclude from this test? Write your conclusions below.

In [ ]:
# p valor es menor que el umbral por lo que podemos rechazar H0 y decir que ambos grupos son independientes


How about we try to compare the different types of pokemon? In the cell below, list the types of Pokemon from column `Type 1` and the count of each type.

In [35]:
pokemon['Type 1'].value_counts()



Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Electric     44
Rock         44
Dragon       32
Ground       32
Ghost        32
Dark         31
Poison       28
Steel        27
Fighting     27
Ice          24
Fairy        17
Flying        4
Name: Type 1, dtype: int64

Since water is the largest group of Pokemon, compare the mean and standard deviation of water Pokemon to all other Pokemon.

In [49]:
water = pokemon[pokemon['Type 1'] == 'Water']
water.describe()


#       Total          HP      Attack     Defense     Sp. Atk  \
count  112.000000  112.000000  112.000000  112.000000  112.000000  112.000000   
mean   303.089286  430.455357   72.062500   74.151786   72.946429   74.812500   
std    188.440807  113.188266   27.487026   28.377192   27.773809   29.030128   
min      7.000000  200.000000   20.000000   10.000000   20.000000   10.000000   
25%    130.000000  328.750000   52.250000   53.000000   54.500000   55.000000   
50%    275.000000  455.000000   70.000000   72.000000   70.000000   70.000000   
75%    456.250000  502.250000   90.250000   92.000000   88.500000   90.500000   
max    693.000000  770.000000  170.000000  155.000000  180.000000  180.000000   

          Sp. Def       Speed  Generation  
count  112.000000  112.000000  112.000000  
mean    70.517857   65.964286    2.857143  
std     28.460493   23.019353    1.558800  
min     20.000000   15.000000    1.000000  
25%     50.000000   50.000000    1.000000  
50%     65.000000   65.000000    3.000000  
75%     89.250000   82.000000    4.000000  
max    160.000000  122.000000    6.000000

Perform a hypothesis test comparing the mean of total points for water Pokemon to all non-water Pokemon. Assume the variances are equal. 

In [48]:
resto = pokemon[pokemon['Type 1'] != 'Water']
resto

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[688 rows x 13 columns]

In [50]:
resto.describe()

#       Total          HP      Attack     Defense     Sp. Atk  \
count  688.000000  688.000000  688.000000  688.000000  688.000000  688.000000   
mean   372.536337  435.859012   68.802326   79.790698   73.988372   72.495640   
std    209.928799  121.091682   25.194299   33.025152   31.719933   33.292537   
min      1.000000  180.000000    1.000000    5.000000    5.000000   10.000000   
25%    197.750000  330.000000   50.000000   55.000000   50.000000   45.000000   
50%    380.000000  450.000000   65.000000   76.000000   70.000000   65.000000   
75%    553.250000  515.000000   80.000000  100.000000   90.000000   95.000000   
max    721.000000  780.000000  255.000000  190.000000  230.000000  194.000000   

          Sp. Def       Speed  Generation  
count  688.000000  688.000000  688.000000  
mean    72.127907   68.654070    3.399709  
std     27.739292   29.925907    1.666119  
min     20.000000    5.000000    1.000000  
25%     50.000000   45.000000    2.000000  
50%     70.000000   65.000000    3.000000  
75%     90.000000   90.000000    5.000000  
max    230.000000  180.000000    6.000000

In [72]:
test2 = ttest_ind(resto['Total'],water['Total'])
test2

Ttest_indResult(statistic=0.4418547448849676, pvalue=0.6587140317488793)

In [64]:
test2.pvalue < 0.05

False

Write your conclusion below.

In [ ]:
#p valor es mayor de 0,05 por lo que no podemos rechazar H0 y ambos grupos pueden ser dependientes.


# Challenge 2 - Matched Pairs Test

In this challenge we will compare dependent samples of data describing our Pokemon. Our goal is to see whether there is a significant difference between each Pokemon's defense and attack scores. Our hypothesis is that the defense and attack scores are equal. In the cell below, import the `ttest_rel` function from `scipy.stats` and compare the two columns to see if there is a statistically significant difference between them.

In [73]:
test3 = ttest_rel(pokemon['Attack'],pokemon['Defense'])
test3

Ttest_relResult(statistic=4.325566393330478, pvalue=1.7140303479358558e-05)

Describe the results of the test in the cell below.

In [56]:
#p valor es menor de 0,05 por lo que podemos rechazar H0 y pueden ser independientes.


We are also curious about whether therer is a significant difference between the mean of special defense and the mean of special attack. Perform the hypothesis test in the cell below. 

In [59]:
pokemon.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [68]:
pokemon['Sp. Atk'].mean()

72.82

In [69]:
pokemon['Sp. Def'].mean()

71.9025

In [74]:
test4 = ttest_rel(72.82,71.9025)
test4

Ttest_relResult(statistic=nan, pvalue=nan)

In [75]:
test3 = ttest_rel(pokemon['Sp. Atk'],pokemon['Sp. Def'])
test3


Ttest_relResult(statistic=0.853986188453353, pvalue=0.3933685997548122)

In [76]:
test3.pvalue < 0.05

False

Describe the results of the test in the cell below.

In [77]:
# No se puede rechazar la hipotesis nula, es decir puede haber diferencia significativa entre muestras


As you may recall, a two sample matched pairs test can also be expressed as a one sample test of the difference between the two dependent columns.

Import the `ttest_1samp` function and perform a one sample t-test of the difference between defense and attack. Test the hypothesis that the difference between the means is zero. Confirm that the results of the test are the same.

In [90]:
test23 = ttest_1samp(pokemon['Attack']-pokemon['Defense'],0)
test23
    

Ttest_1sampResult(statistic=4.325566393330478, pvalue=1.7140303479358558e-05)

In [91]:
test23.pvalue < 0.05
#podemos rechazar h0 y decir que la diferencia puede ser significativa

True

# Bonus Challenge - The Chi-Square Test

The Chi-Square test is used to determine whether there is a statistically significant difference in frequencies. In other words, we are testing whether there is a relationship between categorical variables or rather when the variables are independent. This test is an alternative to Fisher's exact test and is used in scenarios where sample sizes are larger. However, with a large enough sample size, both tests produce similar results. Read more about the Chi Squared test [here](https://en.wikipedia.org/wiki/Chi-squared_test).

In the cell below, create a contingency table using `pd.crosstab` comparing whether a Pokemon is legenadary or not and whether the Type 1 of a Pokemon is water or not.

In [92]:
bonus = pd.crosstab(pokemon['Legendary'], pokemon['Type 1']=='Water')
bonus

Type 1     False  True
Legendary             
False        627   108
True          61     4

In [93]:
chi2_contingency(bonus)

(2.9429200762850503,
 0.08625467249550949,
 1,
 array([[632.1, 102.9],
        [ 55.9,   9.1]]))

In [100]:
ji_dos,pval, dof, ex= chi2_contingency(bonus)
print (ji_dos,pval,dof,ex)

2.9429200762850503 0.08625467249550949 1 [[632.1 102.9]
 [ 55.9   9.1]]


Perform a chi-squared test using the `chi2_contingency` function in `scipy.stats`. You can read the documentation of the function [here](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.chi2_contingency.html).

In [99]:
chi_square=([(f-e)**2./e for f,e in zip(bonus.values, ex)])

chi_statistic=sum(chi_square)

p_value=1-chi2.cdf(x=chi_statistic, df=dof)

p_value

array([0.47668241, 0.07776466])

In [101]:
p_value > 0.05


array([ True,  True])

Based on a 95% confidence, should we reject the null hypothesis?

In [ ]:
# No rechazamos H0 , no existe relacion ninguna entre ambos grupos.

